# Generated by Django 5.0.6 on 2024-06-18 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='foodlist',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=200)),
                ('recipe', models.CharField(max_length=1000)),
                ('food_type', models.CharField(max_length=200)),
                ('recipe_type', models.CharField(max_length=200)),
            ],
        ),
    ]
