# Generated by Django 5.0.6 on 2024-06-19 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodrecipe',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
