# Generated by Django 5.0.6 on 2024-06-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_alter_foodrecipe_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodrecipe',
            old_name='name',
            new_name='recipe_name',
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='ingredients',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='foodrecipe',
            name='method',
            field=models.JSONField(),
        ),
    ]
