# Generated by Django 5.0.6 on 2024-06-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_rename_name_foodrecipe_recipe_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodrecipe',
            name='recipe_type',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
